
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Master Demo - Maarten 
* Environment: Production
* Id: 9779a69d-ee04-01e9-4071-f71a6a27dd65
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = "de-DE" | "default" | "es-ES";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "article"
  | "blog_post"
  | "call_to_action"
  | "disclaimer"
  | "event"
  | "landing_page"
  | "page"
  | "person"
  | "service"
  | "video";

/**
 * Type representing all collections
 */
export type CollectionCodenames = "academic_content" | "default" | "operations" | "patient_resources";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = "academic_resources" | "biographies" | "default" | "patient_resources";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "article_type"
  | "event_topic"
  | "event_type"
  | "general_healthcare_topics"
  | "medical_specialties";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
  | "archived"
  | "copy_review"
  | "draft_97d445e"
  | "draft_a8b162c"
  | "draft_b242d4d"
  | "draft"
  | "legal_review"
  | "marketing_review"
  | "medical_review"
  | "peer_review"
  | "published"
  | "reviewed_1778942"
  | "reviewed"
  | "scheduled"
  | "staff_member_review";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "article_type"
  | "author"
  | "autoplay"
  | "biography"
  | "body_copy"
  | "body"
  | "button_label"
  | "button_link"
  | "caption"
  | "description"
  | "email"
  | "end_date"
  | "event_topic"
  | "event_type"
  | "featured_content"
  | "first_name"
  | "guidelines"
  | "headline"
  | "hero_image"
  | "image_position"
  | "image"
  | "introduction"
  | "job_title"
  | "last_name"
  | "medical_specialties"
  | "metadata__description"
  | "metadata__keywords"
  | "metadata__title"
  | "metadata"
  | "name"
  | "phone"
  | "prefix"
  | "publish_date"
  | "related_articles"
  | "start_date"
  | "subheadline"
  | "subpages"
  | "suffixes"
  | "summary"
  | "team"
  | "title"
  | "topics"
  | "type"
  | "url_slug"
  | "url"
  | "video_link"
  | "website";
