
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏛️ Australian Museum
* Environment: Production
* Id: ab00c5f7-85bf-02cf-55e1-a3d020897258
* 
* -------------------------------------------------------------------------------
**/

export * from "./core.type.ts";
export * from "./delivery.codenames.ts";
