
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Master Demo - Maarten 
* Environment: Production
* Id: 9779a69d-ee04-01e9-4071-f71a6a27dd65
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Article Type
 *
 * Codename: article_type
 * Id: 06a6efd4-18bb-4cfd-973b-cf581fb88f87
 */
export const articleTypeValues = [
  "clinical_guidelines",
  "case_study",
  "research",
  "healthcare_policy_update",
  "institutional_announcement",
  "industry_updates",
  "patient_education",
  "professional_training",
  "educational",
] as const;

/**
 * Type representing Article Type taxonomy
 *
 * Codename: article_type
 * Id: 06a6efd4-18bb-4cfd-973b-cf581fb88f87
 */
export type ArticleType = (typeof articleTypeValues)[number];

/**
 * Type guard for Article Type
 *
 * Codename: article_type
 * Id: 06a6efd4-18bb-4cfd-973b-cf581fb88f87
 */
export function isArticleType(value: string | undefined | null): value is ArticleType {
  return typeof value === "string" && (articleTypeValues as readonly string[]).includes(value);
}
