
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏛️ Australian Museum
* Environment: Production
* Id: ab00c5f7-85bf-02cf-55e1-a3d020897258
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Empty Group
 *
 * Codename: empty_group
 * Id: 84f3bf46-f5cb-40a6-8733-2ee6214e0ff8
 */
export const emptyGroupValues = ["default_term"] as const;

/**
 * Type representing Empty Group taxonomy
 *
 * Codename: empty_group
 * Id: 84f3bf46-f5cb-40a6-8733-2ee6214e0ff8
 */
export type EmptyGroup = (typeof emptyGroupValues)[number];

/**
 * Type guard for Empty Group
 *
 * Codename: empty_group
 * Id: 84f3bf46-f5cb-40a6-8733-2ee6214e0ff8
 */
export function isEmptyGroup(value: string | undefined | null): value is EmptyGroup {
  return typeof value === "string" && (emptyGroupValues as readonly string[]).includes(value);
}
