
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Master Demo - Maarten 
* Environment: Production
* Id: 9779a69d-ee04-01e9-4071-f71a6a27dd65
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Medical Specialties
 *
 * Codename: medical_specialties
 * Id: 22981808-66a0-4d9a-8aa7-4d92f04ead5a
 */
export const medicalSpecialtiesValues = [
  "clinical_research",
  "cardiology",
  "dermatology",
  "endocrinology",
  "experimental_medicine",
  "immunology",
  "infectious_diseases",
  "neurodegenerative_disorders",
  "neurology",
  "oncology",
  "orthopedics",
  "pediatrics",
] as const;

/**
 * Type representing Medical Specialties taxonomy
 *
 * Codename: medical_specialties
 * Id: 22981808-66a0-4d9a-8aa7-4d92f04ead5a
 */
export type MedicalSpecialties = (typeof medicalSpecialtiesValues)[number];

/**
 * Type guard for Medical Specialties
 *
 * Codename: medical_specialties
 * Id: 22981808-66a0-4d9a-8aa7-4d92f04ead5a
 */
export function isMedicalSpecialties(value: string | undefined | null): value is MedicalSpecialties {
  return typeof value === "string" && (medicalSpecialtiesValues as readonly string[]).includes(value);
}
