
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🧔🏻 Personalization Example
* Environment: Production
* Id: c4aa2909-21c3-026b-85f1-89cb4ae991ca
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Personas
 *
 * Codename: personas
 * Id: 927a64c0-3b11-4128-a2cc-10fc5d613574
 */
export const personasValues = ["regular_vistor", "new_vistitor"] as const;

/**
 * Type representing Personas taxonomy
 *
 * Codename: personas
 * Id: 927a64c0-3b11-4128-a2cc-10fc5d613574
 */
export type Personas = (typeof personasValues)[number];

/**
 * Type guard for Personas
 *
 * Codename: personas
 * Id: 927a64c0-3b11-4128-a2cc-10fc5d613574
 */
export function isPersonas(value: string | undefined | null): value is Personas {
  return typeof value === "string" && (personasValues as readonly string[]).includes(value);
}
