
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏛️ Australian Museum
* Environment: Production
* Id: ab00c5f7-85bf-02cf-55e1-a3d020897258
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for General Topics
 *
 * Codename: topic
 * Id: b3628ce6-552f-46e8-aaea-441a2b50e7eb
 */
export const generalTopicsValues = [
  "fossils",
  "minerals",
  "dinosaurs",
  "natural_history",
  "native_animals",
  "marine_life",
  "birds",
  "australian_wildlife",
  "aboriginal_heritage",
  "torres_strait_islander_culture",
  "traditional_arts",
  "indigenous_culture",
  "biodiversity",
  "climate_change",
  "conservation",
  "science___research",
  "school_programs",
  "workshops",
  "public_events",
  "education",
] as const;

/**
 * Type representing General Topics taxonomy
 *
 * Codename: topic
 * Id: b3628ce6-552f-46e8-aaea-441a2b50e7eb
 */
export type GeneralTopics = (typeof generalTopicsValues)[number];

/**
 * Type guard for General Topics
 *
 * Codename: topic
 * Id: b3628ce6-552f-46e8-aaea-441a2b50e7eb
 */
export function isGeneralTopics(value: string | undefined | null): value is GeneralTopics {
  return typeof value === "string" && (generalTopicsValues as readonly string[]).includes(value);
}
