
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🧔🏻 Personalization Example
* Environment: Production
* Id: c4aa2909-21c3-026b-85f1-89cb4ae991ca
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CallToAction } from "./index.ts";
import type { CoreContentType } from "../system/index.ts";

/**
 * A/B CTA
 *
 * Id: a6e25423-df86-486f-935d-2e690974bd0c
 * Codename: a_b_cta
 */
export type ABCTA = CoreContentType<
  ABCTAElementCodenames,
  {
    /**
     * CTA A
     *
     * Type: modular_content
     * Required: true
     * Codename: cta_a
     * Id: f336f4c2-6e6d-4c86-a7d4-a17e784a6682
     */
    readonly cta_a: Elements.LinkedItemsElement<CallToAction>;
    /**
     * CTA B
     *
     * Type: modular_content
     * Required: true
     * Codename: cta_b
     * Id: 6fce759e-cfb0-44be-874a-449c05681e71
     */
    readonly cta_b: Elements.LinkedItemsElement<CallToAction>;
  },
  "a_b_cta"
>;

/**
 * Type representing all available element codenames for A/B CTA
 */
export type ABCTAElementCodenames = "cta_a" | "cta_b";

/**
 * Type guard for A/B CTA
 *
 * Id: a6e25423-df86-486f-935d-2e690974bd0c
 * Codename: a_b_cta
 */
export function isABCTA(item: CoreContentType | undefined | null): item is ABCTA {
  return item?.system?.type === "a_b_cta";
}
