
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🧔🏻 Personalization Example
* Environment: Production
* Id: c4aa2909-21c3-026b-85f1-89cb4ae991ca
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Genre
 *
 * Id: efdd4a35-5613-4901-869f-941a0f2041ae
 * Codename: genre
 */
export type Genre = CoreContentType<
  GenreElementCodenames,
  {
    /**
     * About
     *
     * Type: rich_text
     * Required: false
     * Codename: about
     * Id: 9162562c-52e2-4efa-9a31-faea90892bdd
     */
    readonly about: Elements.RichTextElement<CoreContentType>;
    /**
     * Short Description for the Listener
     *
     * Type: text
     * Required: false
     * Codename: short_description_for_the_listener
     * Id: b54c3499-088c-4db1-851f-0e96418af0b8
     */
    readonly short_description_for_the_listener: Elements.TextElement;
  },
  "genre"
>;

/**
 * Type representing all available element codenames for Genre
 */
export type GenreElementCodenames = "about" | "short_description_for_the_listener";

/**
 * Type guard for Genre
 *
 * Id: efdd4a35-5613-4901-869f-941a0f2041ae
 * Codename: genre
 */
export function isGenre(item: CoreContentType | undefined | null): item is Genre {
  return item?.system?.type === "genre";
}
