
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏛️ Australian Museum
* Environment: Production
* Id: ab00c5f7-85bf-02cf-55e1-a3d020897258
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { AustralianMuseumTopics } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";

/**
 * Reusable Content Block
 *
 * Id: 562dc0a8-a520-4187-97b2-ff108ffa88f4
 * Codename: reusable_content_block
 */
export type ReusableContentBlock = CoreContentType<
  ReusableContentBlockElementCodenames,
  {
    /**
     * Content
     *
     * Type: rich_text
     * Required: false
     * Codename: content
     * Id: 95ec93e2-40df-478c-b100-8b1035318cb4
     */
    readonly content: Elements.RichTextElement<CoreContentType>;
    /**
     * Australian Museum Topics
     *
     * Type: taxonomy
     * Required: false
     * Codename: australian_museum_topics
     * Id: b22a294d-460a-42ab-9fec-1dfc47ee7a68
     */
    readonly australian_museum_topics: Elements.TaxonomyElement<AustralianMuseumTopics, "australian_museum_topics">;
  },
  "reusable_content_block"
>;

/**
 * Type representing all available element codenames for Reusable Content Block
 */
export type ReusableContentBlockElementCodenames = "content" | "australian_museum_topics";

/**
 * Type guard for Reusable Content Block
 *
 * Id: 562dc0a8-a520-4187-97b2-ff108ffa88f4
 * Codename: reusable_content_block
 */
export function isReusableContentBlock(item: CoreContentType | undefined | null): item is ReusableContentBlock {
  return item?.system?.type === "reusable_content_block";
}
