
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Karma Health Master Demo - Maarten 
* Environment: Production
* Id: 9779a69d-ee04-01e9-4071-f71a6a27dd65
* 
* -------------------------------------------------------------------------------
**/

export * from "./metadata.ts";
