
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🧔🏻 Personalization Example
* Environment: Production
* Id: c4aa2909-21c3-026b-85f1-89cb4ae991ca
* 
* -------------------------------------------------------------------------------
**/

export * from "./metadata.ts";
